# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gxq/detect-cars

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gxq/detect-cars

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gxq/detect-cars/CMakeFiles /home/gxq/detect-cars/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gxq/detect-cars/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detect-cars

# Build rule for target.
detect-cars: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 detect-cars
.PHONY : detect-cars

# fast build rule for target.
detect-cars/fast:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/build
.PHONY : detect-cars/fast

detect-cars.o: detect-cars.cpp.o

.PHONY : detect-cars.o

# target to build an object file
detect-cars.cpp.o:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/detect-cars.cpp.o
.PHONY : detect-cars.cpp.o

detect-cars.i: detect-cars.cpp.i

.PHONY : detect-cars.i

# target to preprocess a source file
detect-cars.cpp.i:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/detect-cars.cpp.i
.PHONY : detect-cars.cpp.i

detect-cars.s: detect-cars.cpp.s

.PHONY : detect-cars.s

# target to generate assembly for a file
detect-cars.cpp.s:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/detect-cars.cpp.s
.PHONY : detect-cars.cpp.s

draw.o: draw.cpp.o

.PHONY : draw.o

# target to build an object file
draw.cpp.o:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/draw.cpp.o
.PHONY : draw.cpp.o

draw.i: draw.cpp.i

.PHONY : draw.i

# target to preprocess a source file
draw.cpp.i:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/draw.cpp.i
.PHONY : draw.cpp.i

draw.s: draw.cpp.s

.PHONY : draw.s

# target to generate assembly for a file
draw.cpp.s:
	$(MAKE) -f CMakeFiles/detect-cars.dir/build.make CMakeFiles/detect-cars.dir/draw.cpp.s
.PHONY : draw.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... detect-cars"
	@echo "... detect-cars.o"
	@echo "... detect-cars.i"
	@echo "... detect-cars.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

